Feature/a1 odt 426 vault
catenax-ng/k8s-cluster-stack pull request #11
Opened 2022-03-31 08:05 UTC by csaba-fabian

2022-03-31 08:24 UTC, carslen requested changes
Please refer to comments.

2022-03-31 08:24 UTC, carslen commented on apps/tls/templates/certificate.yaml
> +  namespace: vault
Shouldn't this in any kind parameterized to manager certs for different approaches (argo, vault, etc.)? Applying this, argo won't get its cert, right (when starting with a vanilla k8s cluster) @ricogu

2022-03-31 08:24 UTC, carslen commented on apps/argocd/overlays/core/applicationsets/argo-applicationset.yaml
> +        targetRevision: feature/A1ODT-426-vault
Please flip back to `HEAD` for PR to main branch. Same for the other applicationSet yaml files.

2022-03-31 12:54 UTC, ricogu commented on apps/tls/templates/certificate.yaml
> +  namespace: vault
it will, because the certificate is physically store in secret tls-secret which is replicated across all namespaces <- by reflector

2022-03-31 12:55 UTC, ricogu commented on apps/argocd/overlays/core/applicationsets/argo-applicationset.yaml
> +        targetRevision: feature/A1ODT-426-vault
will do it

2022-03-31 12:57 UTC, ricogu commented on apps/tls/templates/certificate.yaml
> +  namespace: vault
but we can also revert it back to ns argocd, it should have no effect, I will test it

2022-03-31 13:38 UTC, SebastianBezold commented on apps/tls/templates/certificate.yaml
> +  namespace: vault
If this get's replicated to every namespace, wouldn't it then be best to place it in the default namespace, since you cannot be sure if either argocd or vault namespaces are created when applying the helm chart. 
What do you think?

2022-03-31 13:39 UTC, SebastianBezold commented on apps/argocd/overlays/core/applicationsets/certmanager-applicationset.yaml
> +        cluster-name: cx-vault-aks-services-admin
We can freely choose our cluster names in the secret right? If so, could we then choose an easier name like just 'vault-cluster' for example? cx-vault-aks-services-admin sound more like the kubernetes context

2022-03-31 14:10 UTC, ricogu commented on apps/tls/templates/certificate.yaml
> +  namespace: vault
yes, i am also thinking about it as we cannot make sure the other namespace must exist in all cluster (like argocd ns in vault cluster or vault ns in other clusters)

2022-03-31 14:11 UTC, ricogu commented on apps/argocd/overlays/core/applicationsets/certmanager-applicationset.yaml
> +        cluster-name: cx-vault-aks-services-admin
i guess so, we should just change the name of secret

2022-04-01 09:09 UTC, ricogu commented on apps/tls/templates/certificate.yaml
> +  namespace: vault
done

2022-04-01 09:15 UTC, ricogu commented on apps/argocd/overlays/core/applicationsets/certmanager-applicationset.yaml
> +        cluster-name: cx-vault-aks-services-admin
done

2022-04-01 09:59 UTC, ricogu commented on apps/argocd/overlays/core/applicationsets/argo-applicationset.yaml
> +        targetRevision: feature/A1ODT-426-vault
done

2022-04-01 13:19 UTC, carslen approved these changes

2022-04-01 13:20 UTC, merged