feat: Manage hotel budapest projects from core argo
catenax-ng/k8s-cluster-stack pull request #12
Opened 2022-03-31 12:49 UTC by SebastianBezold

- Add all currently existing ArgoCD projects
- Streamline the RBAC configuration on project scope

2022-04-01 12:45 UTC, burakbengi commented on apps/argocd/overlays/core/environments/hotel-budapest.yaml
> +      prune: true
Pruning the hotel with or without customers inside?

2022-04-01 12:45 UTC, burakbengi commented on apps/argocd/overlays/core/kustomization.yaml
> +  - environments/*.yaml
we have an [k8s-cluster-stack](https://github.com/catenax-ng/k8s-cluster-stack/tree/feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo)/[apps](https://github.com/catenax-ng/k8s-cluster-stack/tree/feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo/apps)/[argocd](https://github.com/catenax-ng/k8s-cluster-stack/tree/feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo/apps/argocd)/[overlays](https://github.com/catenax-ng/k8s-cluster-stack/tree/feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo/apps/argocd/overlays)/[core](https://github.com/catenax-ng/k8s-cluster-stack/tree/feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo/apps/argocd/overlays/core)/environments/ and a [k8s-cluster-stack](https://github.com/catenax-ng/k8s-cluster-stack/tree/feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo)/environment/ folder. This structure is a little confusing for me and may be for other as there is only "one character difference" between the folders. May be one of them can get a e.g. "configuration" prefix. Just an idea...

2022-04-01 12:45 UTC, burakbengi commented on environment/hotel-budapest/product-edc.yaml
> +---
a lil' extra just for edc?

2022-04-01 12:45 UTC, burakbengi commented on environment/hotel-budapest/product-edc.yaml
> +---
nvm...  (it's there also for iam team)

2022-04-01 13:54 UTC, SebastianBezold commented on apps/argocd/overlays/core/environments/hotel-budapest.yaml
> +      prune: true
This application will sync the namespaces and ArgoCD projects. If we were to remove a project, because we want to remove access for that specific team, the namespace and project have to be removed. Therefore the prune on automatic sync

2022-04-01 13:58 UTC, SebastianBezold commented on apps/argocd/overlays/core/kustomization.yaml
> +  - environments/*.yaml
We can of course align the both folders and use either environment or environments. If it should be a different name, then i think it should be more specific. The folder in the argocd core overlay will contain ArgoCD Applications syncing specific resources for environments additionally to the Apps, like namespaces for example. The top level environment folder contains this kind of resources.

2022-04-04 07:28 UTC, burakbengi commented on apps/argocd/overlays/core/kustomization.yaml
> +  - environments/*.yaml
I am ok with a more specific name. Actually any name that is self-explanatory and not extremely long.

2022-04-04 14:51 UTC, carslen commented on apps/argocd/overlays/core/kustomization.yaml
> +  - environments/*.yaml
The major question is where to put cluster (aka `overlays/core`) related argo configuration to. From my point of view I would put all cluster related config stuff to `overlays/insert-cluster-name-here` and link it appropriatly in `overlays/insert-cluster-name-here/kustomization.yaml`.

@SebastianBezold prefer to separate it to `/environment/insert-cluster-name-here`. I'd prefer to use one place instead of two.

I guess we'll have to make a decision here.

2022-04-05 11:40 UTC, carslen approved these changes

2022-04-05 13:21 UTC, burakbengi commented on apps/argocd/overlays/core/kustomization.yaml
> +  - environments/*.yaml
Is there any other tradeoff to name for using two or one location?

2022-04-05 13:57 UTC, carslen requested changes

2022-04-05 13:59 UTC, burakbengi commented
Btw. after talking with @Siegfriedk today, we should have the changes from @csaba-fabian under https://github.com/catenax-ng/k8s-cluster-stack/blob/main/apps/tls/ with one default values file and per cluster values file additions:
- [values.yaml](https://github.com/catenax-ng/k8s-cluster-stack/blob/main/apps/tls/values.yaml)
- [values-tls-core.yaml](https://github.com/catenax-ng/k8s-cluster-stack/blob/main/apps/tls/values-tls-core.yaml)
- [values-tls-vault.yaml](https://github.com/catenax-ng/k8s-cluster-stack/blob/main/apps/tls/values-tls-vault.yaml)
- values-...-....yaml

2022-04-05 14:00 UTC, SebastianBezold commented on apps/argocd/overlays/core/environments/app-core.yaml
> +    targetRevision: feature/A10DT-466-manage-hotel-budapest-projects-from-core-argo
done. Thanks for reminding

2022-04-05 14:09 UTC, carslen approved these changes

2022-04-05 14:12 UTC, burakbengi commented on apps/argocd/overlays/core/kustomization.yaml
> +  - environments/*.yaml
I was there. My internet wasn't... :/

2022-04-05 14:13 UTC, merged