Feature/A1ODT-564-defaultBackendService-change
catenax-ng/k8s-cluster-stack pull request #124
Opened 2022-06-24 06:00 UTC by burakbengi

- namespace as variable
- added extra values in alias
- disabled dB ingress
- testing on targetrevision (won't merge with feature name)

2022-06-28 14:31 UTC, SebastianBezold commented
Changes look good to me. We need to test that on an isolated cluster and then change the revisions to HEAD again

2022-06-29 13:28 UTC, carslen requested changes

2022-06-29 13:28 UTC, carslen commented on apps/argocd/overlays/core/environments/dev.yaml
> +    targetRevision: feature/A1ODT-564-defaultBackendService-change
After PR has been approved and merged, the linked branch won't be available anymore (as of repositoriy setting/branch protection _delete branch after merge_). Same for `ingress-applicationset.yaml`.

2022-06-30 07:01 UTC, burakbengi commented on apps/argocd/overlays/core/environments/dev.yaml
> +    targetRevision: feature/A1ODT-564-defaultBackendService-change
Yes, exactly. We first want to create an example cluster for testing, where we can test this branch and than delete these lines. I am not resolving this conversation until that change :)

2022-12-22 13:17 UTC, carslen commented
Implemented with PR #277 and #278

2022-12-22 13:17 UTC, closed without merging