add argocd image updater to dev
catenax-ng/k8s-cluster-stack pull request #153
Opened 2022-07-28 14:10 UTC by ricogu

2022-07-28 14:12 UTC, carslen requested changes
Don't install software to productive systems (at from DevSecOps team point of view) but to DevSecOps-Testing cluster.

2022-07-28 14:14 UTC, ricogu commented
@carslen I added this to overlay of dev cluster, so it will not affect other clusters, is my understanding right?

2022-07-28 14:50 UTC, carslen commented
> @carslen I added this to overlay of dev cluster, so it will not affect other clusters, is my understanding right?

From our point of view the DEV environment is a productive system (of course it's not for the product teams, but for us) where we shall not install SW for internal testing purpose! That's why we setup the [devsecops-testing](https://portal.azure.com/#@catenax.onmicrosoft.com/resource/subscriptions/899135fc-19c6-47cb-82f1-0230af7b99b5/resourceGroups/cx-devsecops-testing-rg/providers/Microsoft.ContainerService/managedClusters/cx-devsecops-testing-aks/overview) cluster next to the other ones.

I won't approve PR when DEV will be target cluster for ArgoCD Image Updater evaluation.

2022-07-28 15:58 UTC, ricogu commented
@carslen changed to testing cluster

2022-07-29 06:56 UTC, ricogu commented on environments/core/applicationsets/argo-applicationset.yaml
> +        targetRevision: HEAD
in order not to make too many tags, I will point the testing cluster to HEAD for sometime, will make a new tag when all changes are confirm and points it to tag again

2022-08-01 06:45 UTC, SebastianBezold approved these changes

2022-08-01 06:57 UTC, merged