Doc/refactor documentation terraforming
catenax-ng/k8s-cluster-stack pull request #193
Opened 2022-09-15 09:37 UTC by kastade

2022-09-15 14:32 UTC, SebastianBezold requested changes

2022-09-15 14:32 UTC, SebastianBezold commented on BOOTSTRAP.md
> -# How to bootstrap a Catena-X environment
Should we really completely remove BOOTSTRAP.md?
I understand, that there is duplicated information, but the initial idea behind this file was to guide someone through the process of setting up an initial cluster, when starting from scratch.
So in my opinion, we need at least a short list of steps (maybe without detailed instructions) that need to be performed, if you do want to deploy our setup, starting with nothing

2022-09-15 14:32 UTC, SebastianBezold commented on terraform/README.md
> +`cd terraform/02_devsecops-testing_cluster`
We should highlight, that you need to initialize terraform at that specific folder, you want to apply terraform config from. It is not only 02_devops-testing_cluster, but all of the cluster folders and also the team onboarding folder.

2022-09-15 14:32 UTC, SebastianBezold commented on terraform/README.md
> +### Removing existing terraform config
This is old information, since at the current setup, most of the state files are stored in an Azure backend (check proivders.tf). Please remove this section, if it no longer applies

2022-09-19 13:15 UTC, carslen commented
Why were YAML files deleted when this PR is about documentation?

2022-09-22 16:35 UTC, carslen commented
I'd prefer to cancel this PR. @catenax-ng/argocdadmins

2022-10-20 09:38 UTC, kastade commented on BOOTSTRAP.md
> -# How to bootstrap a Catena-X environment
have created a short, new, adjusted BOOTSTRAP.md

2022-10-20 09:38 UTC, kastade commented on terraform/README.md
> +`cd terraform/02_devsecops-testing_cluster`
done

2022-10-25 07:27 UTC, SebastianBezold commented
> Why were YAML files deleted when this PR is about documentation?

@carslen I would be ok with removing the both yaml files, since they are example files mixed in our gitops directories. To have some 'templates', we could also use the existing 'real' examples.

What i am not sure about is, if we should move that much information to 'outside' documentation: https://github.com/catenax-ng/catenax-ng.github.io/pull/99/files#diff-d07d4f94863e4205939ebd9fa32a10892a3d4b13b9a0687dcab6d82464ead78b
I would favor having essential documentation as close to where it is needed as possible. This of course does not mean, that having documentation outside as well is a bad idea

2022-10-25 08:02 UTC, carslen commented
> > Why were YAML files deleted when this PR is about documentation?
> 
> @carslen I would be ok with removing the both yaml files, since they are example files mixed in our gitops directories. To have some 'templates', we could also use the existing 'real' examples.

It got clarified in a personal chat, although the question here isn't answered. Recommended also to avoid creating PRs without any description. This would have been a perfect place to explain why the yaml files got deleted.

2022-10-26 08:00 UTC, Siegfriedk commented on BOOTSTRAP.md
> -# How to bootstrap a Catena-X environment
Whats the motivation of the shorter BOOTSTRAP.md? The motivation for the BOOTSTRAP.md was to have one installation guide specific to our infrastructure setting up our infrastructure.

IS this still possible with the changes you maid?

2022-10-26 13:28 UTC, kastade commented on BOOTSTRAP.md
> -# How to bootstrap a Catena-X environment
the general motivation to change some documentation is on the one hand the double and different explanation for 'initialize terraform' and on the other hand the use of information from several documentations to set up an AKS cluster from scratch. The change of 'BOOTSTRAP.md' is based on the comment of September 15 (see above) and the existence of the documentation 'How to setup an AKS Cluster via terraform', which is linked in the BOOTSTRAP.md

2022-10-28 09:05 UTC, Siegfriedk commented on BOOTSTRAP.md
> -# How to bootstrap a Catena-X environment
Is it still possible, with the shorter BOOTSTRAP.md file, to bootstrap our infrastructure?

2022-11-04 11:52 UTC, kastade commented
Did not meet the team's expectations

2022-11-04 11:52 UTC, closed without merging