feat: A1ODT-1029 start to manag forked repo from org eclipse-tractusx
catenax-ng/k8s-cluster-stack pull request #237
Opened 2022-11-10 13:39 UTC by ricogu

2022-11-11 09:25 UTC, SebastianBezold requested changes
This only contains the repositories. We usually also manage the teams access to the repos. Please add that before we can merge this

2022-11-11 09:28 UTC, ricogu commented on terraform/100_team_onboarding/main.tf
> +      team_name : "product-essential-services"
@SebastianBezold  is it not this setting?

2022-11-11 09:29 UTC, SebastianBezold commented on terraform/100_team_onboarding/main.tf
> +      team_name : "product-essential-services"
@ricogu no unfortunately not. since we do have multiple teams that can access the repo, we did that on a separate resource

2022-11-16 13:16 UTC, ricogu commented
@SebastianBezold , I have added the mappings, please review, thanks

2022-11-17 07:58 UTC, SebastianBezold approved these changes
LGTM

2022-11-17 08:17 UTC, merged