feat: change targetrevision for all clusters
catenax-ng/k8s-cluster-stack pull request #246
Opened 2022-11-23 14:22 UTC by almadigabor

change TargetRevision to tag ArgoCD-v2.4.16_AVP-v1.13.0

Draft until [this PR](https://github.com/catenax-ng/k8s-cluster-stack/pull/245) is approved as it is related.

2022-11-24 07:26 UTC, carslen requested changes

2022-11-24 07:26 UTC, carslen commented on environments/core/applicationsets/argo-applicationset.yaml
>          targetRevision: HEAD
Maybe add a comment that DevSecOps is set to `HEAD` by intention. Just to avoid changes in the future.

2022-11-24 08:53 UTC, almadigabor commented on environments/core/applicationsets/argo-applicationset.yaml
>          targetRevision: HEAD
Right, I've added a comment.

2022-11-28 08:14 UTC, SebastianBezold approved these changes

2022-11-28 08:51 UTC, carslen approved these changes

2022-11-28 08:53 UTC, merged