change argocd vault plugin for helm args
catenax-ng/k8s-cluster-stack pull request #50
Opened 2022-04-21 14:27 UTC by ricogu

2022-04-21 14:37 UTC, carslen commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin-helm-args
IMHO there's no need to use this plugin as well as reference it in Line 35-36 as helm is using `values.yaml` file by default. Can You explain why you reference the `values.yaml` file?

I would use:

```yaml
    name: argocd-vault-plugin-helm
    env:
      - name: AVP_SECRET
        value: vault-secret
```

2022-04-21 14:40 UTC, ricogu commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin-helm-args
in this applicationset I have tried to use helm-args

line 35-36
```
- name: helm_args
   value: -f values.yaml
```

this is only enabled in plugin https://github.com/catenax-ng/k8s-cluster-stack/blob/7a6b4e9a9a8504417f79d1c32eea44f0c0f38a82/apps/argocd/base/avp-argocd-cm.yaml#L18

2022-04-21 14:42 UTC, ricogu commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin-helm-args
as @SebastianBezold  has mentioned, we need to provide the flexibility, if in case we would have multiple values.yaml

therefore with helm-algs it can provide multiple values into the helm charts

2022-04-22 06:28 UTC, carslen commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin-helm-args
> as @SebastianBezold has mentioned, we need to provide the flexibility, if in case we would have multiple values.yaml
> 
> therefore with helm-algs it can provide multiple values into the helm charts

You're right, but the _Certmanager_ App doesn't rely on different `values.yaml` files at all. The _Certmanager_ App is the wrong place to showcase the usage of _argocd-vault-plugin-helm-args_. Also for the other helm charts, where currently different `values-*.yaml` files are used, we're not yet done with the dicission if we really require these different ones.

So using the _argocd-vault-plugin-helm_ would be correct as the helm chart will use the `values.yaml` file anyway.

I'd ask you to use AVP plugin matching its intention.

2022-04-22 06:40 UTC, carslen commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin-helm-args
> Can you clarify / explain this a little bit more?
> 
> What use case do we have were we need more than the values.yaml and values-x.yaml?
> 
> @SebastianBezold can you clarify what you both discussed?

Using different `value-*.yaml` files is irrelevant for __this__ App! We should discuss this in correct context, not in this particular PR. Mix up topics will lead to confusion.

2022-04-22 07:40 UTC, ricogu commented
@carslen , please review again

2022-04-22 07:54 UTC, ricogu commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin-helm-args
reverted

2022-04-22 09:02 UTC, carslen requested changes

2022-04-22 09:02 UTC, carslen commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin
This won't work. As this is a helm chart you've to use _argocd-vault-plugin-helm_.

2022-04-22 09:10 UTC, ricogu commented on environments/core/applicationsets/certmanager-applicationset.yaml
> +          name: argocd-vault-plugin
fixed

2022-04-22 09:11 UTC, carslen approved these changes

2022-04-22 09:19 UTC, merged