Feature/rico add ingress
catenax-ng/k8s-cluster-stack pull request #6
Opened 2022-03-29 09:20 UTC by ricogu

- add cluster issuer, wilrdcard certificate
- add reflector

2022-03-29 13:17 UTC, SebastianBezold commented on apps/argocd/overlays/core/applicationsets/reflector-applicationset.yaml
> +      ignoreDifferences: # https://github.com/argoproj/argo-cd/issues/4276#issuecomment-908455476
I guess this is a copy-paste leftover. If so, please remove it

2022-03-29 13:17 UTC, SebastianBezold commented on apps/tls/Chart.yaml
> +name: cluster-base
We should adjust this name as well

2022-03-29 13:44 UTC, carslen requested changes

2022-03-29 13:44 UTC, carslen commented on apps/tls/values-tls.yaml
> +  email: "yuanxun.gu@sap.com"
do we have any more general mail address available than your personal mail address for this purpose? This seems to be wrong for me.

2022-03-29 14:18 UTC, ricogu commented on apps/tls/values-tls.yaml
> +  email: "yuanxun.gu@sap.com"
an email from catena-x is the best but I am not aware of that

2022-03-29 14:23 UTC, ricogu commented on apps/argocd/overlays/core/applicationsets/reflector-applicationset.yaml
> +        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
done

2022-03-29 14:25 UTC, ricogu commented on apps/tls/values-tls.yaml
> +  email: "yuanxun.gu@sap.com"
suggestion? @carslen

2022-03-30 07:53 UTC, carslen commented on apps/tls/values-tls.yaml
> +  email: "yuanxun.gu@sap.com"
Unless there is no better solution right now, keep the personal address until we've found a better solution.

2022-03-30 07:56 UTC, ricogu commented on apps/tls/values-tls.yaml
> +  email: "yuanxun.gu@sap.com"
sure, please approve then

2022-03-30 07:56 UTC, carslen approved these changes

2022-03-30 09:17 UTC, merged